/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Vz1TTj65QYi
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

'use client';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { useState } from 'react';

export function DemoPage() {
  const [comments, setComments] = useState([
    {
      title: "Airplane Turbulence: Sky's Rollercoaster",
      name: '@iamwillpursell',
      content:
        'I really love the ecosystem Vercel is creating. The way each component can be added and modified with ease really makes these tools attractive.',
    },
    {
      title: 'How to make a chat app with React',
      name: '@HackSoft',
      content:
        'We are more than excited to leverage all the new stuff, building better products for our clients ✨',
    },
    {
      title: 'Cooking recipe for disaster',
      name: '@greed7513',
      content:
        'does anyone know which monospace are they using when showing code?',
    },
  ]);

  const [newComment, setNewComment] = useState({
    title: '',
    name: '',
    content: '',
  });

  const handleInputChange = (e: any) => {
    const { id, value } = e.target;
    setNewComment((prev) => ({
      ...prev,
      [id]: value,
    }));
  };

  const handleSubmit = async (e: any) => {
    e.preventDefault();
    if (newComment.title && newComment.name && newComment.content) {
      setComments((prev) => [newComment, ...prev]);
      setNewComment({ title: '', name: '', content: '' });
    }
  };

  return (
    <div className="flex h-screen flex-col">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <h1 className="text-2xl font-bold">Comment Board Demo</h1>
      </header>
      <main className="flex-1 overflow-y-auto px-4 py-8">
        <div className="w-full max-w-2xl space-y-4 mx-auto">
          {comments.map((comment, index) => (
            <div
              key={index}
              className="flex flex-col gap-2 bg-white p-4 rounded shadow"
            >
              <div className="font-medium">{comment.title}</div>
              <div className="text-muted-foreground">{comment.name}</div>
              <div>{comment.content}</div>
            </div>
          ))}
        </div>
      </main>
      <div className="bg-muted px-4 py-6">
        <form
          className="w-full max-w-2xl mx-auto space-y-4"
          onSubmit={handleSubmit}
        >
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="space-y-2">
              <Label htmlFor="title">Title</Label>
              <Input
                id="title"
                placeholder="Enter a title"
                value={newComment.title}
                onChange={handleInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="name">Name</Label>
              <Input
                id="name"
                placeholder="Enter your name"
                value={newComment.name}
                onChange={handleInputChange}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="comment">Comment</Label>
              <Textarea
                id="content"
                placeholder="Enter your comment"
                rows={2}
                value={newComment.content}
                onChange={handleInputChange}
              />
            </div>
          </div>
          <div className="flex justify-end">
            <Button type="submit">Submit</Button>
          </div>
        </form>
      </div>
    </div>
  );
}
